sudo: required

services:
  - docker
  
install:
  - docker build -t theballkyo/php-fpm7:test 7.0/FPM/
  - docker run -p 9001:9000 --name phpfpm7 -d theballkyo/php-fpm7:test

script:
  - docker ps | grep -q phpfpm7